// Code generated by Slice Machine. DO NOT EDIT.

import { defineSliceZoneComponents } from '#imports';
import { defineAsyncComponent } from 'vue';

export const components = defineSliceZoneComponents({
  code: defineAsyncComponent(() => import('./Code/index.vue')),
  content: defineAsyncComponent(() => import('./Content/index.vue')),
  gallery: defineAsyncComponent(() => import('./Gallery/index.vue')),
});
